### ISSUE TITLE
Auth & Sign Out

### ISSUE THREAD

**Issue by johnvehr** [rootstrap/rails_api_base#293] opened 2021-03-17 20:52 UTC
Sign in and then immediately sign out should get a success response if the sing in was a success. However getting a 404 user not found or logged in. 

If i sign up and then immediately sign out all is fine. Only on sign in 

<img width="428" alt="Screen Shot 2021-03-17 at 2 51 52 PM" src="https://user-images.githubusercontent.com/1425013/111536805-55a52b80-8730-11eb-8177-fb25398cc02a.png">

**Comment by santib** [comment] 2024-02-01 18:30
Sorry it took too long. I'm closing it because I couldn't reproduce it, please provide more information and steps to reproduce. Thanks

**Closed by santib** 2024-02-01 18:30 UTC
Labels: bug
