### ISSUE TITLE
Devise Token Auth Issue: IndexError: string not matched

### ISSUE THREAD

**Issue by MaicolBen** [rootstrap/rails_api_base#73] opened 2017-08-11 17:39 UTC
It is wrong closed in https://github.com/lynndylanhurley/devise_token_auth/issues/681, the workaround is https://stackoverflow.com/questions/38424068/devise-token-auth-rails-5-indexerror-string-not-matched

**Comment by MaicolBen** [comment] 2017-09-19 19:42
Fixed with #85

**Comment by MaicolBen** [comment] 2017-12-20 17:39
This happens also when the user logouts, we need to find the root cause of the problem, for now, you can apply this solution:
```
User.find_each |user|
  user.uid = user.email
  user.tokens = nil
  user.save!
end
```

**Comment by fedeagripa** [comment] 2020-01-28 17:04
@santib closing this cause the root cause was adding token as `text` instead of `json` that  de serializable and so no error occur

**Closed by fedeagripa** 2020-01-28 17:04 UTC
Labels: bug
